### PR TITLE
Fix NullPointerException

### PR DESCRIPTION
**Pull request by prt2121**
Hey,

I think the issue is not related to Fingerprint API. It's just that you reference the view which doesn't exist in the xml. `findViewById` returns `null`. I've tested the app and Fingerprint works fine. See PR for details.

### CODE REVIEW

**Comment by ericcarboni** [comment]
Thanks for much for all the help! What device are you running it on? It is still crashing on my Samsung phone.

**Comment by prt2121** [comment]
I ran on an emulator API-23. testing the fingerprint with `adb -s <emulator-ID> emu finger touch <fingerprint ID>` command.

**Comment by ericcarboni** [comment]
I figured that was the case. I'm trying to make it backwards compatible and am testing on a device with a lower SDK. The API was said to be able to work with the support library though, so I guess I'll just keep at it.

**Comment by prt2121** [comment]
hope Samsung updates to Marshmallow soon!

**Comment by ericcarboni** [comment]
Ha! Not gonna hold my breath.

**Pull request merged**
